---
# handlers file for nginx
- name: restart nginx
  service:
    name: nginx
    state: restarted
  # Ignore errors due to: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=754762;msg=9
  ignore_errors: yes